;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Character",NewTagName="Ability")
+GameplayTagRedirects=(OldTagName="Weapons.Ranged.Stuff",NewTagName="Weapons.Ranged.Staff")
+GameplayTagRedirects=(OldTagName="GameplayCue.AOEDangerZone",NewTagName="GameplayCue.AOE")
+GameplayTagRedirects=(OldTagName="GameplayCue.AOE.CurseRock",NewTagName="GameplayCue.AOE.BlackHole")
+GameplayTagList=(Tag="Ability",DevComment="")
+GameplayTagList=(Tag="Ability.Death",DevComment="")
+GameplayTagList=(Tag="Ability.Defensive.Shield",DevComment="")
+GameplayTagList=(Tag="Ability.HitReaction",DevComment="")
+GameplayTagList=(Tag="Ability.MeleeAttack.Katana",DevComment="")
+GameplayTagList=(Tag="Ability.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="Ability.RangedAttack.AOEAttack",DevComment="")
+GameplayTagList=(Tag="Ability.RangedAttack.AOEAttack.Curse",DevComment="")
+GameplayTagList=(Tag="Ability.RangedAttack.AOEAttack.Fire",DevComment="")
+GameplayTagList=(Tag="Ability.RangedAttack.AOEAttack.Ice",DevComment="")
+GameplayTagList=(Tag="Ability.RangedAttack.ShootMagicProjectile",DevComment="")
+GameplayTagList=(Tag="Ability.RangedAttack.ShootMagicProjectile.Curse",DevComment="")
+GameplayTagList=(Tag="Ability.RangedAttack.ShootMagicProjectile.Fire",DevComment="")
+GameplayTagList=(Tag="Ability.RangedAttack.ShootMagicProjectile.Ice",DevComment="")
+GameplayTagList=(Tag="Ability.ToggleWeapon",DevComment="")
+GameplayTagList=(Tag="Cooldown.AOEAttack.Ice",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Cooldown.Shield",DevComment="")
+GameplayTagList=(Tag="Data.Armor",DevComment="")
+GameplayTagList=(Tag="Data.Cooldown",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Data.Shield",DevComment="")
+GameplayTagList=(Tag="Data.Strength",DevComment="")
+GameplayTagList=(Tag="Debuff.Curse",DevComment="")
+GameplayTagList=(Tag="Debuff.Fire",DevComment="")
+GameplayTagList=(Tag="Debuff.Ice",DevComment="")
+GameplayTagList=(Tag="Effects.DoHitReaction",DevComment="")
+GameplayTagList=(Tag="Elements.Curse",DevComment="")
+GameplayTagList=(Tag="Elements.Fire",DevComment="")
+GameplayTagList=(Tag="Elements.Ice",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.LevelUp",DevComment="")
+GameplayTagList=(Tag="Event.AbilityActivation.Dash",DevComment="")
+GameplayTagList=(Tag="Event.AbilityActivation.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="Event.AbilityActivation.MeleeAttack.Katana",DevComment="")
+GameplayTagList=(Tag="Event.AbilityActivation.RangedAttack.Staff",DevComment="")
+GameplayTagList=(Tag="Event.AbilityActivation.ToggleWeapon",DevComment="")
+GameplayTagList=(Tag="Event.AbilityAttackLogic",DevComment="")
+GameplayTagList=(Tag="Event.Combo.NextAttack",DevComment="")
+GameplayTagList=(Tag="Event.Combo.Reset",DevComment="")
+GameplayTagList=(Tag="Event.Element",DevComment="")
+GameplayTagList=(Tag="Event.Element.Changed",DevComment="")
+GameplayTagList=(Tag="Event.HitTrace",DevComment="")
+GameplayTagList=(Tag="Event.HitTrace.End",DevComment="")
+GameplayTagList=(Tag="Event.HitTrace.Start",DevComment="")
+GameplayTagList=(Tag="Event.InputWindow.End",DevComment="")
+GameplayTagList=(Tag="Event.InputWindow.Start",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Trigger",DevComment="")
+GameplayTagList=(Tag="Event.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="Event.Talent.Granted",DevComment="")
+GameplayTagList=(Tag="Event.Talent.LevelUp",DevComment="")
+GameplayTagList=(Tag="Event.ToggleWeapon.End",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AfterImage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AOE",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AOE.BlackHole",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AOE.DangerZone",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AOE.DangerZone.Curse",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AOE.DangerZone.Fire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AOE.DangerZone.Ice",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AOE.FireMeteor",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AOE.GiantSnowball",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Buff.Shield",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MagicAttack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MagicAttack.Curse",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MagicAttack.Curse.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MagicAttack.Curse.Spawn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MagicAttack.Fire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MagicAttack.Fire.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MagicAttack.Fire.Spawn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MagicAttack.Ice",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MagicAttack.Ice.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MagicAttack.Ice.Spawn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MeleeAttack.Katana",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Death",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Status.Burn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Status.Curse",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Status.Freeze",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Whoosh.Katana",DevComment="")
+GameplayTagList=(Tag="ReactiveAbility.Freeze",DevComment="")
+GameplayTagList=(Tag="ReactiveAbility.StaminaRegen",DevComment="")
+GameplayTagList=(Tag="State.Action.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Action.ToggleWeapon.Equipping",DevComment="")
+GameplayTagList=(Tag="State.Action.ToggleWeapon.Unequipping",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="Status.Burned",DevComment="")
+GameplayTagList=(Tag="Status.Cursed",DevComment="")
+GameplayTagList=(Tag="Status.Frozen",DevComment="")
+GameplayTagList=(Tag="Status.Shield",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")
+GameplayTagList=(Tag="Talent.Active.AOEAttack",DevComment="")
+GameplayTagList=(Tag="Talent.Active.MagicAttack",DevComment="")
+GameplayTagList=(Tag="Talent.Active.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="Weapons.Melee.Axe",DevComment="")
+GameplayTagList=(Tag="Weapons.Melee.Katana",DevComment="")
+GameplayTagList=(Tag="Weapons.Ranged.Staff",DevComment="")

