;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Character",NewTagName="Ability")
+GameplayTagRedirects=(OldTagName="Weapons.Ranged.Stuff",NewTagName="Weapons.Ranged.Staff")
+GameplayTagList=(Tag="Ability",DevComment="")
+GameplayTagList=(Tag="Ability.MeleeAttack.Katana",DevComment="")
+GameplayTagList=(Tag="Ability.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="Ability.RangedAttack.AOEAttack",DevComment="")
+GameplayTagList=(Tag="Ability.RangedAttack.AOEAttack.Ice",DevComment="")
+GameplayTagList=(Tag="Ability.RangedAttack.ShootMagicProjectile",DevComment="")
+GameplayTagList=(Tag="Ability.ToggleWeapon",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Damage",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Heal",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.AbilityActivation.Dash",DevComment="")
+GameplayTagList=(Tag="Event.AbilityActivation.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="Event.AbilityActivation.MeleeAttack.Katana",DevComment="")
+GameplayTagList=(Tag="Event.AbilityActivation.RangedAttack.Staff",DevComment="")
+GameplayTagList=(Tag="Event.AbilityActivation.ToggleWeapon",DevComment="")
+GameplayTagList=(Tag="Event.AbilityAttackLogic",DevComment="")
+GameplayTagList=(Tag="Event.Combo.NextAttack",DevComment="")
+GameplayTagList=(Tag="Event.Combo.Reset",DevComment="")
+GameplayTagList=(Tag="Event.HitTrace",DevComment="")
+GameplayTagList=(Tag="Event.HitTrace.End",DevComment="")
+GameplayTagList=(Tag="Event.HitTrace.Start",DevComment="")
+GameplayTagList=(Tag="Event.InputWindow.End",DevComment="")
+GameplayTagList=(Tag="Event.InputWindow.Start",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Trigger",DevComment="")
+GameplayTagList=(Tag="Event.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="GameplayCue.AfterImage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MagicAttack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MagicAttack.Hit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MagicAttack.Spawn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")
+GameplayTagList=(Tag="State.Action.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Action.Attacking.AOEAttack",DevComment="")
+GameplayTagList=(Tag="State.Action.ToggleWeapon.Equipping",DevComment="")
+GameplayTagList=(Tag="State.Action.ToggleWeapon.Unequipping",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")
+GameplayTagList=(Tag="Weapons.Melee.Axe",DevComment="")
+GameplayTagList=(Tag="Weapons.Melee.Katana",DevComment="")
+GameplayTagList=(Tag="Weapons.Ranged.Staff",DevComment="")

